Repository PoojaMittal2842/Delhi-Tourism, pull requests merged in 2021-03, with the labels that each got.

#97 Places by Category (Front End) #90
  Assets/css/Category.css
  Assets/images/Camping sites.jpg
  Assets/images/Social Places.jpg
  Assets/images/Travel.jpg
  Assets/images/food.jpeg
  Assets/images/red-fort-delhi-india-indian-flag-84125101.jpg
  Category.html
  css/index.css
  img/Garden of Five Senses.jpg
  index.html
Labels: GSSoC'21, Level1

#103 added login page
  Assets/images/login.jpg
  login.html
Labels: GSSoC'21, Level1

#100 Created Home Page, Navbar, favicon
  Assets/css/home.css
  Assets/js/home.js
  home.html
Labels: GSSoC'21, Level1

#111 Modified words and spelling
  README.md
Labels: GSSoC'21, Level0

#106 Created the Home Page
  Assets/css/home.css
  Assets/images/amusement.jpg
  Assets/images/amusement1.jpg
  Assets/images/delhi.jpg
  Assets/images/flower.jpg
  Assets/images/kid.jpg
  Assets/images/kid1.jpg
  Assets/images/kid2.jpg
  Assets/images/lotus1.jpg
  Assets/images/lotus2.jpg
  Assets/images/lotus3.jpg
  Assets/images/museum.jpg
  Assets/images/museum1.jpg
  Assets/images/redfort1.jpg
  Assets/images/redfort2.jpg
  Assets/images/redfort3.jpg
  Assets/images/shopping.jpg
  Assets/images/shopping1.jpg
  home.html
Labels: GSSoC'21, Level1

#108 Tourist places of Delhi
  gallery.html
  images/aksha.jpg
  images/humayun.jpg
  images/india_gate.jpg
  images/jama-masjid-delhi.jpg
  images/jm.jpg
  images/lodhi.jpg
  images/lotus-temple.jpg
  images/qutab_minar.jpg
  images/rajghat.jpg
  images/rb.jpg
  images/smriti.jpg
  images/the-red-fort-delhi.jpg
  images/zoo.jpg
  style.css
Labels: GSSoC'21, Level1

#126 Book Pass Commit
  Book_pass.html
Labels: GSSoC'21, Level0

#130 Browse Places Page(Front end)
  Browse Places Page(Front end)/index.html
  Browse Places Page(Front end)/india gate.jpg
  Browse Places Page(Front end)/jama masjid.jpg
  Browse Places Page(Front end)/jantar mantar.jpg
  Browse Places Page(Front end)/lotus temple.jpg
  Browse Places Page(Front end)/qutub minar.jpg
  Browse Places Page(Front end)/red fort.jpg
  Browse Places Page(Front end)/script.js
  Browse Places Page(Front end)/style.css
Labels: GSSoC'21, Level1

#127 issue #89 - contact us page added
  Assets/css/contact.css
  contactus.html
Labels: GSSoC'21, Level1

#124 Connected all pages together + created about us page
  Assets/css/Book_pass.css
  Assets/css/about_us.css
  Assets/css/home.css
  Assets/css/registration.css
  Assets/js/home.js
  Book_pass.html
  about_us.html
  home.html
  registration.html
Labels: GSSoC'21, Level1

#131 Styling and Animation of Index Page
  Assets/css/style.css
  index.html
Labels: GSSoC'21, Level3

#139 Modified the Contact Us Page
  Assets/css/contact.css
  contactus.html
Labels: GSSoC'21, Level1

#144 added styles for creating card overlay
  Assets/css/style.css
  css/index.css
Labels: GSSoC'21, Level1

#149 Header Alignment & Removed old files
  home.html
  index.html
Labels: GSSoC'21, Level1

#161 Responsive Admin Dashboard
  Admin Page/.vscode/settings.json
  Admin Page/assets/tuat.jpg
  Admin Page/fontawesome-free/css/all.css
  Admin Page/fontawesome-free/css/all.min.css
  Admin Page/fontawesome-free/css/brands.css
  Admin Page/fontawesome-free/css/brands.min.css
  Admin Page/fontawesome-free/css/fontawesome.css
  Admin Page/fontawesome-free/css/fontawesome.min.css
  Admin Page/fontawesome-free/css/regular.css
  Admin Page/fontawesome-free/css/regular.min.css
  Admin Page/fontawesome-free/css/solid.css
  Admin Page/fontawesome-free/css/solid.min.css
  Admin Page/fontawesome-free/css/svg-with-js.css
  Admin Page/fontawesome-free/css/svg-with-js.min.css
  Admin Page/fontawesome-free/css/v4-shims.css
  Admin Page/fontawesome-free/css/v4-shims.min.css
  Admin Page/fontawesome-free/webfonts/fa-brands-400.eot
  Admin Page/fontawesome-free/webfonts/fa-brands-400.svg
  Admin Page/fontawesome-free/webfonts/fa-brands-400.ttf
  Admin Page/fontawesome-free/webfonts/fa-brands-400.woff
  Admin Page/fontawesome-free/webfonts/fa-brands-400.woff2
  Admin Page/fontawesome-free/webfonts/fa-regular-400.eot
  Admin Page/fontawesome-free/webfonts/fa-regular-400.svg
  Admin Page/fontawesome-free/webfonts/fa-regular-400.ttf
  Admin Page/fontawesome-free/webfonts/fa-regular-400.woff
  Admin Page/fontawesome-free/webfonts/fa-regular-400.woff2
  Admin Page/fontawesome-free/webfonts/fa-solid-900.eot
  Admin Page/fontawesome-free/webfonts/fa-solid-900.svg
  Admin Page/fontawesome-free/webfonts/fa-solid-900.ttf
  Admin Page/fontawesome-free/webfonts/fa-solid-900.woff
  Admin Page/fontawesome-free/webfonts/fa-solid-900.woff2
  Admin Page/index.html
  Admin Page/index.js
  Admin Page/style.css
  Assets/css/style.css
Labels: GSSoC'21, Level4

#159 Fixed search button and added Search filter
  Assets/css/Book_ticket.css
  Assets/css/Category.css
  Assets/css/browse_place.css
  Assets/css/style.css
  Assets/js/browse_place.js
  Pages/Browse_Place.html
  index.html
Labels: GSSoC'21, Level3

#166 Dark Mode of Admin Page
  Admin Page/index.html
  Admin Page/index.js
Labels: GSSoC'21, Level2

#165 Icons added in contact us section and link in email of contact us page
  Pages/contactus.html
  index.html
Labels: GSSoC'21, Level2

#163 Update README.md
  README.md
Labels: GSSoC'21, Level0

#174 Added Light Dark mode in all the pages
  Assets/css/Book_ticket.css
  Assets/css/browse_place.css
  Assets/css/change_password.css
  Assets/css/registration.css
  Assets/css/style.css
  Assets/js/Book_ticket.js
  Assets/js/browse_place.js
  Assets/js/main.js
  Assets/js/registration.js
  Pages/Book_ticket.html
  Pages/Browse_Place.html
  Pages/changepassword.html
  Pages/login.html
  Pages/registration.html
  index.html
Labels: GSSoC'21, Level2

#181 Linked footer tags and Gallery button
  index.html
Labels: GSSoC'21, Level1

#182 Adding small description to footer (issue #170)
  index.html
Labels: GSSoC'21, Level0

#185 Updated contactus page (issue #167)
  Pages/contactus.html
Labels: GSSoC'21, Level0
