Repository PoojaMittal2842/Delhi-Tourism, pull requests merged in 2021-04, with the labels that each got.

#203 Quick Booking Section
  public/User_Assets/css/style.css
  public/User_Assets/js/bootstrap-datepicker.js
  public/User_Assets/js/main.js
  views/User/index.ejs
Labels: GSSoC'21, Level2

#205 Register page fix #202
  app.js
  public/User_Assets/js/registration.js
  views/User/registration.ejs
Labels: GSSoC'21, Level1

#211 Modify theme toggle - #209
  public/User_Assets/css/Book_ticket.css
  public/User_Assets/css/browse_place.css
  public/User_Assets/css/change_password.css
  public/User_Assets/css/registration.css
  public/User_Assets/css/style.css
  public/User_Assets/js/Book_ticket.js
  public/User_Assets/js/browse_place.js
  public/User_Assets/js/main.js
  public/User_Assets/js/registration.js
  views/User/Book_ticket.ejs
  views/User/Browse_Place.ejs
  views/User/changepassword.ejs
  views/User/index.ejs
  views/User/login.ejs
  views/User/registration.ejs
Labels: GSSoC'21, Level2

#225 Changes in Review
  public/User_Assets/css/style.css
  views/User/index.ejs
Labels: GSSOC21, Level1

#223 Linked all CSS, JS, Images according to the backend structure
  Trash/about_us.css
  Trash/about_us.html
  Trash/gallery.html
  Trash/home.css
  Trash/home.html
Labels: GSSOC21, Level1

#224 Changed the header of the Book_ticket page and created partials and boilerplate
  public/User_Assets/css/Book_ticket.css
  views/User/Book_ticket.ejs
  views/layouts/boilerplate.ejs
  views/partials/footer.ejs
  views/partials/navbar.ejs
Labels: GSSOC21, Level1

#226 Added the Login-Register Functionality
  app.js
  models/Readme.txt
  models/user.js
  views/User/index.ejs
  views/User/login.ejs
  views/User/registration.ejs
Labels: GSSOC21, Level3

#230 Responsive Blog checking page for Admin
  app.js
  public/Admin_Assets/blog.css
  views/Admin/blog.ejs
  views/Admin/index.ejs
Labels: GSSOC21, Level3

#234 add feedback form
  public/User_Assets/css/feedback.css
  views/User/index.ejs
Labels: GSSOC21, Level2

#235 Added Flash Messages Functionality with light-dark ui to the Login- Register Pages
  app.js
  node_modules/connect-flash/.travis.yml
  node_modules/connect-flash/LICENSE
  node_modules/connect-flash/README.md
  node_modules/connect-flash/lib/flash.js
  node_modules/connect-flash/lib/index.js
  node_modules/connect-flash/package.json
  package-lock.json
  package.json
  public/validateForms.js
  views/User/login.ejs
  views/User/registration.ejs
Labels: GSSOC21, Level3
